[pytest]
# norecursedirs = tests/da_saltare tests/vecchi
# Oppure usa ignore per file specifici
addopts =
    --ignore=tests/test_jsonld.py
    --ignore=tests/test_impostazioni.py
    --ignore=tests/test_openings_simple.py
    --ignore=tests/test_robots.py